### ISSUE TITLE
Not working with ImageView inside

### ISSUE THREAD

**Issue by Sroka** [captain-miao/OptionRoundCardview#3]
Hi, thanks for this library. I tried to use it but unfortunately it is not rounding the corners of its contents when I put ImageView inside. Support Library's CardView does so.

**Comment by captain-miao** [comment]
Can you show me the detail-layout?

Maybe add layout_margin to OptRoundCardView.

**Comment by captain-miao** [comment]
It's work after add marginBottom in OptRoundCardView, just add space to show Card shadow.
