### ISSUE TITLE
Card elevation shadow cut 

### ISSUE THREAD

**Issue by jordyamc** [captain-miao/OptionRoundCardview#4]
The Card elevation shadow is cut when is inside another view on Android >= Lollipop

I need the Card as a Recycleview but i need some elements behind the card so i wraped all in RelativeView, but the Card shadow shows as cut

![photo_2017-09-02_13-04-32](https://user-images.githubusercontent.com/6831873/29997684-5f1aedb8-8fdf-11e7-8364-b4ff1b8110c8.jpg)

**Comment by captain-miao** [comment]
It's work after add marginBottom in OptRoundCardView, just add space to show Card shadow.

I have committed in example.
```
        android:layout_marginLeft="4dp"
        android:layout_marginRight="4dp"
        android:layout_marginTop="4dp"
        android:layout_marginBottom="4dp"
        app:optRoundCardCornerRadius="2dp"
```
