### ISSUE TITLE
Background colour not behaving same as support cards

### ISSUE THREAD

**Issue by niknetniko** [captain-miao/OptionRoundCardview#5]
The support library [CardView](https://android.googlesource.com/platform/frameworks/support/+/refs/heads/master/v7/cardview/src/main/java/android/support/v7/widget/CardView.java)s use following code to set the default background:

```java

ColorStateList backgroundColor;
if (a.hasValue(R.styleable.CardView_cardBackgroundColor)) {
    backgroundColor = a.getColorStateList(R.styleable.CardView_cardBackgroundColor);
} else {
    // There isn't one set, so we'll compute one based on the theme
    final TypedArray aa = getContext().obtainStyledAttributes(COLOR_BACKGROUND_ATTR);
    final int themeColorBackground = aa.getColor(0, 0);
    aa.recycle();

    // If the theme colorBackground is light, use our own light color, otherwise dark
    final float[] hsv = new float[3];
    Color.colorToHSV(themeColorBackground, hsv);
    backgroundColor = ColorStateList.valueOf(hsv[2] > 0.5f
    ? getResources().getColor(R.color.cardview_light_background)
    : getResources().getColor(R.color.cardview_dark_background));
}
```

Perhaps it would be nice if the OptionRoundCardview did this as well? I use this library in an app where we are currently implementing a night mode, and adding this code would make the OptionRoundCardview adjust automatically to light and dark themes.

**Comment by captain-miao** [comment]
yes, add DayNight mode, upgrade 1.1.0, but not enough test.

```'com.github.captain-miao:optroundcardview:1.1.0'```
